version: '3.8'

services:
  frontend:
    image: oiramalli/simple-frontend-angular-express
    ports:
      - "80:3000"
    depends_on:
      - estado-bd
    networks:
      - main-network

#   micro-servicio-1:
#     image: <nombre_de_usuario>/<nombre_de_contenedor>
#     # Exponemos el puerto 80 para que sea accesible para los otros servicios.
#     expose:
#       - "80"
#     depends_on:
#       - servicio-db
      
#   micro-servicio-2:
#     image: <nombre_de_usuario>/<nombre_de_contenedor>
#     # Exponemos el puerto 80 para que sea accesible para los otros servicios.
#     expose:
#       - "80"
#     depends_on:
#       - servicio-db
      
#   micro-servicio-3:
#     image: <nombre_de_usuario>/<nombre_de_contenedor>
#     # Exponemos el puerto 80 para que sea accesible para los otros servicios.
#     expose:
#       - "80"
#     depends_on:
#       - servicio-db

  estado-bd:
    image: oiramalli/db-test
    # Exponemos el puerto 80 para que sea accesible para los otros servicios.
    restart: always
    expose:
      - "80"
    # Para mapear el contenedor a nuestra computadora podemos descomentar la siguiente línea
    # ports:
    #   - "8080:80"
    depends_on:
      - database
    networks:
      - main-network
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
        - ${MYSQL_DATA}:/var/lib/mysql
    restart: always
    expose: 
        - "3306"
    # Para mapear el contenedor a nuestra computadora podemos descomentar la siguiente línea
    # ports:
    #   - "3306:3306"
    networks:
      - main-network
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
networks:
  main-network:
    name: main-network